# Generated by Django 6.0.6 on 2026-06-10 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_spend_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('top_merchants', models.JSONField(default=list)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('narrative', models.TextField()),
                ('risk_level', models.CharField(max_length=20)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(max_length=100)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('llm_category', models.CharField(blank=True, max_length=100, null=True)),
                ('llm_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jobs.job')),
            ],
        ),
    ]
